CREATE TABLE NEWS
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  TITLE VARCHAR2(100) NOT NULL,
  NEWS_DATE DATE NOT NULL,
  BRIEF VARCHAR2(500) NOT NULL,
  CONTENT VARCHAR2(2048) NOT NULL
);

CREATE SEQUENCE  "LUNTIK"."NEWS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;

create or replace TRIGGER NEWS_TRIGGER
BEFORE INSERT ON NEWS
REFERENCING NEW AS NEW
FOR EACH ROW
  BEGIN
    SELECT news_seq.nextval INTO :NEW.ID FROM dual;
  END;

ALTER TRIGGER NEWS_TRIGGER ENABLE;



INSERT INTO NEWS (ID, TITLE, NEWS_DATE, BRIEF, CONTENT )
VALUES (DEFAULT, 'news_title', TO_DATE('22.06.2005 12:13:12','dd.mm.yyyy hh24.mi.ss'), 'briefly bla bla bla',
        'content bla bla bla text text text');