CREATE TABLE ANDREY.NEWS 
(
  ID INTEGER NOT NULL
,TITLE VARCHAR(100) NOT NULL
, NEWS_DATE DATE NOT NULL
, BRIEF VARCHAR(500) NOT NULL 
, CONTENT VARCHAR(2048) NOT NULL 
, CONSTRAINT NEWS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN ANDREY.NEWS.NEWS_DATE IS 'current date of news';

COMMENT ON COLUMN ANDREY.NEWS.BRIEF IS 'brief content of news';

COMMENT ON COLUMN ANDREY.NEWS.CONTENT IS 'full content of news';


CREATE SEQUENCE S_NEWS
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE OR REPLACE TRIGGER T_NEWS_ID
BEFORE INSERT
ON NEWS
REFERENCING NEW AS NEW
FOR EACH ROW
  BEGIN
    if(:new.ID is null) then
      SELECT S_NEWS.nextval
      INTO :new.ID
      FROM dual;
    end if;
  END;
/

ALTER TRIGGER "T_NEWS_ID" ENABLE;


INSERT INTO ANDREY.NEWS (ID, TITLE, NEWS_DATE, BRIEF, CONTENT )
VALUES (DEFAULT, 'news_title', TO_DATE('22.06.2005 12:13:12','dd.mm.yyyy hh24.mi.ss'), 'briefly bla bla bla',
        'content bla bla bla text text text');