--DROP TABLE "LUNTIK"."NEWS";

CREATE TABLE "LUNTIK"."NEWS"
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  TITLE VARCHAR2(100) NOT NULL,
  NEWS_DATE DATE NOT NULL,
  BRIEF VARCHAR2(500) NOT NULL,
  CONTENT VARCHAR2(2048) NOT NULL
);

